# This is a basic workflow to help you get started with Actions

name: Copy ssh keys

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      user_name:
        description: User name
        required: true
      ssh_pub_key:
        description: Your public key
        required: true
      password:
        description: User password
        required: true
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: ssh to target server
        run: ssh ubuntu@10.0.64.122
  create_user:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: create new user
        run: |
          #!/bin/bash
          ssh ubuntu@10.0.64.122<<EOF
            username=${{ github.event.inputs.user_name }}
            password=${{ github.event.inputs.password }}
            if id ${{ github.event.inputs.user_name }} &>/dev/null; then
              echo "User already exists"
            else
            sudo useradd -m ${{ github.event.inputs.user_name }}
            

            echo "${{ github.event.inputs.user_name }}:${{ github.event.inputs.password }}" | sudo chpasswd

            echo "User ${{ github.event.inputs.user_name }} has been created with password"
            fi
            echo -e "${{ github.event.inputs.ssh_pub_key }}\n" >> /home/ubuntu/.ssh/authorized_keys
          EOF

           


      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
          #echo Add other actions to build,
          #echo test, and deploy your project.
